### PR TITLE
Fix - under some conditions translation string wasn't collected

### LINKED ISSUE #19: Strings aren't parsed correctly (php)
I faced some missing translations for some php files, probably due to the fact that strings aren't parsed correctly

This is an example:
```
array(
		"title" => __( 'Zoom', '3d-product-viewer' ),
		"text"  => __( "Use the mouse wheel to zoom in or out on the model", '3d-product-viewer' ),
		"icon"  => 'icon-zoom'
)
```

### PR DESCRIPTION
**Pull request by erikyo**
closes an issue that happened to me due to strings that were not being processed correctly I assume the reason was the missing check for the 'encapsed_string' type 

close #19

### CODE REVIEW

File: src/parser/tree.ts [hunk 1]
```diff
@@ -97,30 +99,35 @@ export function doTree(
...
 
-				// skip if it's not a string
-				if (node.type !== "string") continue
+				if (node?.type === ',') {
+					// skip the comma between arguments
+					continue
+				} else if (stringType.includes(node?.type)) {
+					// unquote the strings
+					nodeValue = nodeValue.slice(1, -1)
+				}
```
Comment (johnhooks) [inline src/parser/tree.ts:121]: @erikyo why do an `else if` here? If this isn't true, shouldn't we not continue?
```suggestion
				}
				
				if (stringType.includes(node?.type)) {
					// unquote the strings
					nodeValue = nodeValue.slice(1, -1)
				} else {
				  // unexpected node type
				  continue
				}
```

Comment (johnhooks) [reply src/parser/tree.ts:121]: Or if we hit and unexpected node type, perhaps we shouldn't complete the translation, and should flag it to warn about improper use of the function.

Comment (erikyo) [reply src/parser/tree.ts:121]: tested locally but seems that this change can introduce a new glitch, problably because that values aren't a "string" type
image

i'll look into to find the correct names

Comment (erikyo) [reply src/parser/tree.ts:121]: the missing types (using a really wide base of plugins and themes so i'm quite sure that i'm covering all the possible cases):

- shell_command_expression -> `This is a ${bug}` (with the "`" quotes)
- function_call_expression -> count( %s ) 
- variable_name -> $variable
- name -> it's a js variable


@johnhooks what do you suggest with those types? aren't supported but as you said we should provide a fallback. why not use that replacing the continue with a console.warn?

Comment (johnhooks) [reply src/parser/tree.ts]: @erikyo i would agree that if an unknown type is encountered, it should be logged, and not translation not included in the output.

Comment (erikyo) [reply src/parser/tree.ts]: ok then... you are right! i'll add back the `continue`, but a will also keep the `console.warn` in order to inform the user about the reason of the missing translation

File: src/parser/tree.ts [hunk 2]
```diff
@@ -97,32 +99,55 @@ export function doTree(
...
+							node?.type + // variable_name
+							' is ' +
+							translationKeys[translationKeyIndex] + // in number
+							' for  ' +
+							nodeValue + // for $number
+							' in ' +
+							filepath // in filename.php
+					)
+					// this string is not translatable and should be skipped
+					continue
```
Comment (johnhooks) [inline src/parser/tree.ts:136]: I would think we don't skip the single string but the whole translation with a `return`.

Comment (erikyo) [reply src/parser/tree.ts:136]: no it would only exit from the nested function, feel free to update the code... it's "more" correct as you say!
